### ISSUE TITLE
Stopping only local Kafka will leave SR running, but UI will show nothing is running.

### ISSUE THREAD

**Issue by derek1ee** [confluentinc/vscode#674] opened 2024-11-22 20:19 UTC
1. Start local Kafka + SR.
2. Stop just Kafka.
3. Observe resource list and docker status.

Actual:
1. Extension shows nothing is running.
<img width="316" alt="Screenshot 2024-11-22 at 12 19 12 PM" src="https://github.com/user-attachments/assets/6c609ec3-026d-4663-b9da-aaca10418036">

2. Docker runtime shows SR is still running.
<img width="729" alt="Screenshot 2024-11-22 at 12 17 35 PM" src="https://github.com/user-attachments/assets/a4fd1f87-b8ec-4479-90db-812344f84aa2">

Expected:
1. Either show SR is still running.
2. Or stop SR when Kafka is stopped.

**Comment by shouples** [comment] 2024-11-22 22:31
Tempted to close this one since we have https://github.com/confluentinc/vscode/issues/537, but what should the expected behavior here be? For extension-managed SR, it isn't usable if it doesn't have the associated Kafka container backing.

**Comment by shouples** [comment] 2024-11-25 18:37
We should try auto-checking SR if Kafka is selected, more general updates to the quickpick, related to https://github.com/confluentinc/vscode/issues/673

**Comment by shouples** [comment] 2024-12-10 00:43
Closing this since (on `main`) it's no longer possible to only stop Kafka via the extension as of https://github.com/confluentinc/vscode/pull/713

**Closed by shouples** 2024-12-10 00:43 UTC
Labels: triaged, usability, needs discussion
