### ISSUE TITLE
Report an Issue window disappears

### ISSUE THREAD

**Issue by roberto-molinari** [confluentinc/vscode#223] opened 2024-09-17 21:21 UTC
Type: <b>Bug</b>

Not sure exactly how I did it, but after clicking "Report an Issue" in the Support section of the left nav menu, the actual Issue Reporter window got hidden.

Because of this, I thought the Report an Issue functionality was broken as I could not find the Issue Reporter window.

Suggestions/ideas
* make Issue Reporter modal so its always on top
* if its not modal, bring it to the top whenever the user clicks on Report an Issue

Extension version: 0.15.3
VS Code version: Code 1.93.1 (Universal) (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 7, 7|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id a94e9292-2792-4272-bb61-f29756bd22e9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
autoexpandse:31133494
ei213698:31121563

```

</details>

**Comment by shouples** [comment] 2024-09-17 21:32
@roberto-molinari I think we can close this one since it appears to be a duplicate of https://github.com/confluentinc/vscode/issues/222, and unfortunately we don't have control over that Issue Reporter window since it's a built-in VS Code feature and not something our extension contributes.

**Closed** 2024-09-18 15:32 UTC
Labels: duplicate
