### ISSUE TITLE
Confluent Cloud Resources do not load

### ISSUE THREAD

**Issue by roberto-molinari** [confluentinc/vscode#224] opened 2024-09-17 21:25 UTC
Type: <b>Bug</b>

After I log in to my Confluent Cloud account via the VS Code Plugin, I get "no resources found." in the Resources section of the left nav

I expect to see my environments, clusters, etc.

Note that when I click "Select Kafka Cluster" in the Topics section of the left nav, I do get presented with a list of the clusters in my confluent.cloud account (so some level of connection is working)

Extension version: 0.15.3
VS Code version: Code 1.93.1 (Universal) (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 6, 7|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|--crash-reporter-id a94e9292-2792-4272-bb61-f29756bd22e9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
autoexpandse:31133494
ei213698:31121563

```

</details>

**Comment by shouples** [comment] 2024-09-17 21:28
@roberto-molinari thanks for bringing this up! Are you using Google/GitHub SSO for logging in, or username/password?

And if you're able to reproduce this behavior, do you still see `No resources found` after clicking the Refresh action on the Resources view?
<img width="331" alt="image" src="https://github.com/user-attachments/assets/fde741b6-0bca-44ca-824a-e3ab9fe74983">

**Comment by roberto-molinari** [comment] 2024-09-24 18:58
@shouples - I log in to confluent cloud using username/password

Yes, the problem is reproduceable (I've actually never had the Resources pane work)

And yes, happens even after I use the Refresh button

**Comment by shouples** [comment] 2024-09-26 13:52
Got it, thanks @roberto-molinari -- we'll add some handling for this issue in the upcoming release to help triage what's going on here since there seems to be an issue loading your CCloud environments for the default organization. Will keep you posted once we get the next version published to the marketplace.

**Comment by roberto-molinari** [comment] 2024-10-17 15:22
Works now, thanks!

**Comment by shouples** [comment] 2024-10-17 20:33
@roberto-molinari do your CCloud resources (environments and clusters) load properly now, or are you seeing an error notification?

**Comment by roberto-molinari** [comment] 2024-10-17 21:32
Resources are loading now

And at least all the environments, kafka clusters and schema registry instances that I see in the web ui are also showing in the vs code ui

**Comment by shouples** [comment] 2024-10-21 17:01
Great to hear! I'm going to close this one, and we can revisit if folks are seeing error notifications mentioned above and/or are missing resources that they may see in CCloud.

**Closed by shouples** 2024-10-21 17:01 UTC
Labels: bug
